package com.capestone.enums;

public enum NotificationType {

    // Proposal
    NEW_PROPOSAL_SUBMITTED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    ADDITIONAL_DETAILS_REQUIRED,
    CUSTOMER_RESPONSE_RECEIVED,

    // Quote
    QUOTE_GENERATED,

    // Policy
    POLICY_ACTIVATED,
    POLICY_EXPIRING,
    POLICY_EXPIRED,

    // Claim
    CLAIM_SUBMITTED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_ADDITIONAL_DETAILS_REQUIRED,
    CLAIM_CUSTOMER_RESPONSE_RECEIVED,

    // General
    GENERAL_ALERT
}