from enum import Enum

class Role(Enum):
    ADMIN = "ADMIN"
    CUSTOMER = "CUSTOMER"
    INSURANCE_OFFICER = "INSURANCE_OFFICER"

class JobTitle(Enum):
    ASSOCIATE_EXECUTIVE = "ASSOCIATE_EXECUTIVE"
    MANAGER = "MANAGER"
    SENIOR_EXECUTIVE = "SENIOR_EXECUTIVE"
    TECHNICAL_EXECUTIVE = "TECHNICAL_EXECUTIVE"

class VehicleCategory(Enum):
    TRUCK = "TRUCK"
    MOTORCYCLE = "MOTORCYCLE"
    CAMPER_VAN = "CAMPER_VAN"
    CAR = "CAR"
    BIKE = "BIKE"

class FuelType(Enum):
    PETROL = "PETROL"
    DIESEL = "DIESEL"
    CNG = "CNG"
    LPG = "LPG"
    ELECTRIC = "ELECTRIC"
    HYBRID = "HYBRID"

class VehicleUsage(Enum):
    PRIVATE = "PRIVATE"
    COMMERCIAL = "COMMERCIAL"

class VehicleCondition(Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    FAIR = "FAIR"
    POOR = "POOR"
    DAMAGED = "DAMAGED"

class PolicyStatus(Enum):
    PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    QUOTE_GENERATED = "QUOTE_GENERATED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"

class ClaimStatus(Enum):
    SUBMITTED = "SUBMITTED"
    OFFERED = "OFFERED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"

class PaymentStatus(Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    VERIFIED = "VERIFIED"
